version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo Test Run

  build:
    commands:
      - ls
      - echo Zipping LF1
      - cd Lambda-Code
      - zip -r ../LF1.zip LF1.py
      - aws s3 cp ../LF1.zip s3://code-pipeline-bucket-540
      - echo Zipping search-photos
      # - cd ../search-photos
      - zip -r ../search-photos.zip search-photos.py
      - aws s3 cp ../search-photos.zip s3://code-pipeline-bucket-540

  post_build:
    commands:
      - echo Updating Lambda function Code
      - aws lambda update-function-code --function-name LF1 --s3-bucket code-pipeline-bucket-540 --s3-key LF1.zip
      - aws lambda update-function-code --function-name search-photos --s3-bucket code-pipeline-bucket-540 --s3-key search-photos.zip