version: 0.2

phases:
  build:
    commands:
      - echo "Preparing to deploy frontend to S3..."

  post_build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync Cloud_Assignment_3_Website/Website-Code/ s3://b1-ass3 