version: 0.2

phases:

  pre_build:
    commands:
      - echo Test Run

  build:
    commands:
      - ls
      - echo Zipping Indexing Lambda function
      - cd Lambda-Code/Indexing-Code
      - zip -r indexing-lambda.zip lambda_function.py
      - aws s3 cp indexing-lambda.zip s3://code-pipeline-bucket-540
      - echo Zipping Search Photos Lambda function
      - cd ../SearchPhotos-Code
      - zip -r search-photos-lambda.zip lambda_function.py
      - aws s3 cp search-photos-lambda.zip s3://code-pipeline-bucket-540

  post_build:
    commands:
      - echo Updating Lambda function Code
      - aws lambda update-function-code --function-name LF1 --s3-bucket code-pipeline-bucket-540 --s3-key LF1.zip
      - aws lambda update-function-code --function-name search-photos --s3-bucket code-pipeline-bucket-540 --s3-key search-photos.zip